spring:
  application:
    name: driver-management
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/pios_driver_management
    username: postgres
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration/drivermanagement
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated

server:
  port: 8081
