package com.pios.networkmanagement.domain

/**
 * Identity of a Person aggregate (Sprint 7A: PIOS Network Foundation).
 * Unlike [com.pios.drivermanagement.domain.DriverId] or Order Management's
 * `OrderId`, a Person's id is never caller-supplied — it is generated by
 * [com.pios.networkmanagement.application.CreatePersonApplicationService]
 * on creation (see that class's own KDoc), since no external system
 * assigns a person an identity before PIOS does.
 */
@JvmInline
value class PersonId(val value: String) {
    init {
        require(value.isNotBlank()) { "PersonId must not be blank" }
    }
}
