package com.pios.identity.application

import com.pios.identity.domain.IdentityId
import com.pios.identity.domain.Phone
import com.pios.identity.domain.PhoneVerificationChallenge
import com.pios.identity.domain.PhoneVerificationPurpose
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Component
import java.security.SecureRandom
import java.time.Duration
import java.time.Instant
import java.util.UUID

/**
 * ADR-082 (D-03), C-2 revision — the shared OTP-issuance step behind both
 * `POST /v1/identities/recovery/request` and
 * `POST /v1/identities/me/phone/verify/request`.
 *
 * C-2 architectural change: this class no longer calls [OutboundSmsPort]
 * directly. Instead, after persisting the challenge row it inserts a PENDING
 * row into [SmsOutboxRepository] — atomically in the same transaction.
 * [SmsOutboxRelay] (scheduled separately) claims the row, decrypts the OTP
 * ciphertext, calls [OutboundSmsPort], and transitions to SENT/FAILED/UNKNOWN.
 *
 * The OTP plaintext exists in heap memory only for the duration of this call:
 * 1. Generated by [generateCode].
 * 2. Hashed with [passwordHasher] → stored in challenge row (D-03.7).
 * 3. Encrypted with [otpCipher] → stored in challenge row as [PhoneVerificationChallenge.otpCiphertext].
 * 4. Immediately discarded. Never logged (D-03.7). Never written to any
 *    other column, table, or log.
 *
 * The challenge + outbox INSERT must be one atomic transaction so that a
 * crash between the two writes can never leave a challenge without its
 * corresponding outbox row (which would produce a live, undeliverable OTP).
 *
 * [challengeGuard] is taken first, before supersede/insert — found necessary,
 * not assumed: two concurrent first-ever requests for the same (identity,
 * purpose) can both find nothing to supersede and both attempt to insert,
 * without it (see [PhoneVerificationChallengeGuard]'s own KDoc).
 */
@Component
class PhoneVerificationChallengeIssuer(
    private val challengeRepository: PhoneVerificationChallengeRepository,
    private val passwordHasher: PasswordHasher,
    private val otpCipher: OtpCipher,
    private val smsOutboxRepository: SmsOutboxRepository,
    private val transactionRunner: TransactionRunner = NoOpTransactionRunner,
    @Value("\${pios.identity.otp.ttl-seconds:600}") private val ttlSeconds: Long,
    @Value("\${pios.identity.otp.max-attempts:10}") private val maxAttempts: Int,
    @Value("\${pios.identity.otp.code-digits:6}") private val codeDigits: Int,
    private val challengeGuard: PhoneVerificationChallengeGuard = NoOpPhoneVerificationChallengeGuard
) {
    private val secureRandom = SecureRandom()

    fun issue(identityId: IdentityId, phone: Phone, purpose: PhoneVerificationPurpose) {
        val code = generateCode()
        transactionRunner.run {
            challengeGuard.lock(identityId, purpose)
            val now = Instant.now()
            challengeRepository.supersedeLive(identityId, purpose, now)
            smsOutboxRepository.cancelPendingForSuperseded(identityId.value, purpose.name, now)

            val hashed = passwordHasher.hash(code)
            val encrypted = otpCipher.encrypt(code) // plaintext exists only here

            val challengeId = UUID.randomUUID().toString()
            challengeRepository.save(
                PhoneVerificationChallenge(
                    id = challengeId,
                    identityId = identityId,
                    phone = phone,
                    purpose = purpose,
                    codeHash = hashed.hash,
                    codeSalt = hashed.salt,
                    iterations = hashed.iterations,
                    attemptCount = 0,
                    maxAttempts = maxAttempts,
                    createdAt = now,
                    expiresAt = now.plus(Duration.ofSeconds(ttlSeconds)),
                    consumedAt = null,
                    supersededAt = null,
                    otpCiphertext = encrypted.ciphertext,
                    otpNonce = encrypted.nonce
                )
            )

            // Atomic: outbox row inserted in the same transaction as the
            // challenge row. A relay-crash after commit leaves both rows
            // consistent; a crash before commit rolls back both.
            smsOutboxRepository.insert(
                SmsOutboxRecord(
                    id = null,
                    challengeId = challengeId,
                    status = SmsOutboxStatus.PENDING,
                    leaseUntil = null,
                    claimToken = null,
                    nextAttemptAt = now,
                    providerMessageId = null,
                    sentAt = null,
                    failureReason = null,
                    retryCount = 0,
                    createdAt = now,
                    updatedAt = now
                )
            )
        }
        // No SMS call here. The relay handles delivery asynchronously.
    }

    private fun generateCode(): String {
        val bound = Math.pow(10.0, codeDigits.toDouble()).toInt()
        val value = secureRandom.nextInt(bound)
        return value.toString().padStart(codeDigits, '0')
    }
}
