package com.pios.identity.domain

/**
 * Identity of an [Identity] aggregate (ADR-038). Never caller-supplied —
 * generated by [com.pios.identity.application.CreateIdentityApplicationService]
 * on creation, the same convention
 * [com.pios.networkmanagement.domain.PersonId] already established: no
 * external system assigns an identity before PIOS does.
 */
@JvmInline
value class IdentityId(val value: String) {
    init {
        require(value.isNotBlank()) { "IdentityId must not be blank" }
    }
}
